### ISSUE TITLE
"export 'isCssAnimationSupported' was not found in 'css-animation' WARNING

### ISSUE THREAD

**Issue by YukSeungChan** [react-component/time-picker#70]
I using rc-time-picker 2.4.1

I get an warning when webpack building.

```
WARNING in ./node_modules/rc-animate/es/AnimateChild.js
76:11-34 "export 'isCssAnimationSupported' was not found in 'css-animation'
    at HarmonyImportSpecifierDependency._getErrors (/Users/loup/Workspace/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/loup/Workspace/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/loup/Workspace/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/loup/Workspace/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/loup/Workspace/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/loup/Workspace/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/loup/Workspace/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/loup/Workspace/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by yesmeck** [comment]
Could you provide a reproduction repo?
